### ISSUE TITLE
Regarding training resource requirements

### ISSUE THREAD

**Issue by Pefect96** [Code-kunkun/ZS-CIR#4]
Great Job! 
I would like to ask about the computational resources required for training and the training time.

**Comment by Code-kunkun** [comment]
Hello, thank you for your interest in our work. 
The computational resources depend on the specific backbone used and the batch size. If CLIP is used as the backbone, 3090 is enough. If BLIP is used as the backbone, about 40G of memory may be needed. 
In terms of training time, because of our setting, it can be completed in about a few hours.

**Comment by Pefect96** [comment]
OK, thanks!
